''' How many distinct terms are in the sequence generated by a**b for 2 ≤ a ≤
100 and 2 ≤ b ≤ 100? '''

def main():
    ''' Calculate all values, check how many are unique '''
    terms = set()
    for a in range(2, 101):
        for b in range(2, 101):
            terms.add(a**b)
    print(len(terms))

if __name__ == "__main__":
    main()
